name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "master" ]
  pull_request:
    # branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ssh-key : ${{ secrets.CONAN_CONFIG_DEPLOY_KEY }}
          repository: Paultergeist/conan-config
          ref: sample1
          path: conan-config

      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.2

      - name: conan config install
        run: |
          conan config install ./conan-config
          conan remote list
          conan profile list

    #   - name: Build
    #     run: |
    #       conan create .