name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  trigger_master:
    uses: Paultergeist/gha_master/.github/workflows/basic.yml@master
    with:
      caller_repo: ${{ github.repository }}
      caller_branch: ${{ github.ref_name }}
      caller_ref: ${{ github.ref }}
      # ref: ${{ github.ref }}
      # ref_name: ${{ github.ref_name }}
      
